import sqlite3
conn = sqlite3.connect('database.db')
cursor = conn.cursor()
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print("Tables:", cursor.fetchall())
cursor.execute("PRAGMA table_info(users)")
print("Users table info:", cursor.fetchall())
cursor.execute("SELECT * FROM users")
print("Users data:", cursor.fetchall())
conn.close()
